DECLARE
    V_ID           NUMBER;
    V_ITEM_BARCODE NUMBER;
BEGIN
    SELECT
        ITEM_ID INTO V_ID
    FROM
        ODBC_JHC.JHC_INVDATA JI
    WHERE
        FOREIGN_ITEM_CODE = :V_ITEM_SKU;
    SELECT
        ITEM_MAIN_BARCODE INTO V_ITEM_BARCODE
    FROM
        ODBC_JHC.JHC_INVDATA JI
    WHERE
        FOREIGN_ITEM_CODE = :V_ITEM_SKU;
    INSERT INTO JHC.INV_STORE_TRANS_DTL(
        COMPANY_ID,
        TRANS_ID,
        OPEN_TRANS_NO,
        SERIAL_ID,
        STORE_ID,
        ITEM_ID,
        TRANS_UNIT,
        TRANS_QUANT,
        BASE_UNIT,
        TRANS_BASE_QUANT,
        TRANS_AMOUNT_CURR,
        TRANS_AMOUNT_BASE,
        EXCHANGE_BASE_FACTOR,
        CURRENCY_ID,
        IS_POSTED,
        USER_CREATE,
        PC_NAME_CREATE,
        DATE_CREATED,
        UNIT_EXCHANGE_FACTOR,
        ITEM_CODE,
        DTL_TRANS_STATUS,
        DTL_TRANS_DATE,
        TAX_ID,
        TAX_PERCENT_AMOUNT,
        TAX_VALUE,
        TAX_AMOUNT,
        PRICE_NOTAX,
        ORG_PRICE,
        PRICE_WTAX,
        COST_PRICE,
        TAX_AMOUNT_BASE,
        PRICE_NOTAX_BASE,
        PRICE_WTAX_BASE,
        BASE_ITEM_BARCODE,
        FOREIGN_ITEM_CODE,
        FIRST_DISC_PER,
        SECOND_DISC_PER,
        SECOND_DISC_AMT,
        REFUND_BASE_QUANT,
        TRANS_PACK_COUNT,
        INT_NO_PACKS,
        REMAIN_NO_PACKS,
        DISCOUNT_AMOUNT_BASE,
        MAS_DISCOUNT_AMOUNT,
        MAS_DISCOUNT_AMOUNT_BASE,
        FIRST_DISC_AMT_BASE,
        SECOND_DISC_AMT_BASE,
        BASE_UNIT_PRICE_NOTAX,
        REFUND_UNIT_EXCHANGE,
        ROW_ORDER
    ) VALUES (
        2,
        13,
        :V_OPEN_TRANS_NO,
        :V_SERIAL_ID,
        :V_STORE_ID,
        V_ID,
        1,
        :V_TRANS_QUANTITY,
        1,
        1,
        :V_TRANS_AMOUNT_CURR,
        :V_TRANS_AMOUNT_BASE,
        1,
        1,
        0,
        22,
        'Automatic',
        TO_CHAR(SYSDATE, 'DD-Mon-YY'),
        1,
        V_ID,
        3,
        TO_CHAR(SYSDATE, 'DD-Mon-YY'),
        16,
        1,
        16,
        :V_TAX_AMOUNT,
        :V_PRICE_NOTAX,
        0,
        :V_PRICE_WTAX,
        0,
        :V_TAX_AMOUNT_BASE,
        :V_PRICE_NOTAX_BASE,
        :V_PRICE_WTAX_BASE,
        V_ITEM_BARCODE,
        :V_ITEM_SKU,
        :V_DISC_PER,
        0,
        0,
        0,
        24,
        0,
        1,
        0,
        :V_MAS_DISCOUNT_AMOUNT,
        :V_MAS_DISCOUNT_AMOUNT_BASE,
        :V_FIRST_DISC_AMT_BASE,
        :V_SECOND_DISC_AMT_BASE,
        :V_BASE_UNIT_PRICE_NOTAX,
        1,
        :V_ROW_ORDER
    );
END;